language: php

php:
  - 7.4
  - 8.0

before_install:
  # Turn off XDebug
  - phpenv config-rm xdebug.ini || return 0

install:
  # Install dependencies
  - travis_retry composer install --no-progress --prefer-dist

script:
  # Tests
  - make tests

after_failure:
  # Print *.actual content
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
  include:
    - stage: Quality Assurance
      php: 7.4
      script:
        - make qa

    - stage: Test Coverage
      if: branch = master AND type = push
      php: 7.4
      script:
        - make coverage
      after_script:
        - composer require php-coveralls/php-coveralls ^2.1.0
        - vendor/bin/php-coveralls --verbose --config tests/.coveralls.yml

    - stage: Outdated Dependencies
      if: branch = master AND type = cron
      php: 7.4
      script:
        - composer outdated --direct

  allow_failures:
    - stage: Test Coverage
    - php: 8.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
